<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Data golongan pelanggan sesuai dengan Keputusan Bupati
     * dan requirement PDF yang diberikan dengan tarif per blok yang akurat
     */
    public function run(): void
    {
        $customerGroups = [
            // Golongan 1 - Sosial (Tarif Rendah)
            [
                'code' => '1L1',
                'name' => 'Lembaga Pendidikan/Kesehatan Pemerintah',
                'category' => 'Lembaga',
                'description' => 'Sekolah, Rumah Sakit, Puskesmas milik pemerintah',
                'block1_rate' => 1800,
                'block2_rate' => 2100,
                'block3_rate' => 2400,
                'block4_rate' => 2700,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1R1',
                'name' => 'Rumah Tinggal Sangat Sederhana',
                'category' => 'Rumah',
                'description' => 'Rumah dengan kriteria sangat sederhana',
                'block1_rate' => 1600,
                'block2_rate' => 1900,
                'block3_rate' => 2200,
                'block4_rate' => 2500,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1R2',
                'name' => 'Rumah Tinggal Sederhana',
                'category' => 'Rumah',
                'description' => 'Rumah dengan kriteria sederhana',
                'block1_rate' => 2000,
                'block2_rate' => 2300,
                'block3_rate' => 2600,
                'block4_rate' => 2900,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1R3',
                'name' => 'Rumah Susun Sederhana',
                'category' => 'Rumah',
                'description' => 'Apartemen atau rumah susun sederhana',
                'block1_rate' => 2200,
                'block2_rate' => 2500,
                'block3_rate' => 2800,
                'block4_rate' => 3100,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1S1',
                'name' => 'Badan Amal/Sosial',
                'category' => 'Sosial',
                'description' => 'Organisasi amal dan sosial',
                'block1_rate' => 1500,
                'block2_rate' => 1800,
                'block3_rate' => 2100,
                'block4_rate' => 2400,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1S2',
                'name' => 'Kran Umum',
                'category' => 'Sosial',
                'description' => 'Kran umum untuk keperluan masyarakat',
                'block1_rate' => 1200,
                'block2_rate' => 1500,
                'block3_rate' => 1800,
                'block4_rate' => 2100,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '1S3',
                'name' => 'Rumah Ibadat',
                'category' => 'Sosial',
                'description' => 'Masjid, Gereja, dan tempat ibadah lainnya',
                'block1_rate' => 1400,
                'block2_rate' => 1700,
                'block3_rate' => 2000,
                'block4_rate' => 2300,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],

            // Golongan 2 - Menengah (Tarif Sedang)
            [
                'code' => '2L1',
                'name' => 'Lembaga Pemerintah Bukan Lembaga Usaha',
                'category' => 'Lembaga',
                'description' => 'Kantor pemerintah non-komersial',
                'block1_rate' => 3500,
                'block2_rate' => 4000,
                'block3_rate' => 4500,
                'block4_rate' => 5000,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '2L2',
                'name' => 'Lembaga Pendidikan/Kesehatan',
                'category' => 'Lembaga',
                'description' => 'Sekolah dan rumah sakit swasta',
                'block1_rate' => 3200,
                'block2_rate' => 3700,
                'block3_rate' => 4200,
                'block4_rate' => 4700,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '2L3',
                'name' => 'Lembaga Pemerintah Lainnya TNI/POLRI',
                'category' => 'Lembaga',
                'description' => 'Fasilitas TNI/POLRI',
                'block1_rate' => 3300,
                'block2_rate' => 3800,
                'block3_rate' => 4300,
                'block4_rate' => 4800,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '2N1',
                'name' => 'Niaga dan Jasa Kecil',
                'category' => 'Niaga',
                'description' => 'Usaha niaga dan jasa skala kecil',
                'block1_rate' => 4800,
                'block2_rate' => 5500,
                'block3_rate' => 6200,
                'block4_rate' => 6900,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '2R1',
                'name' => 'Rumah Tinggal Menengah',
                'category' => 'Rumah',
                'description' => 'Rumah dengan kriteria menengah',
                'block1_rate' => 7100, // Sesuai dengan contoh di gambar
                'block2_rate' => 8500, // Sesuai dengan contoh di gambar
                'block3_rate' => 9500, // Sesuai dengan contoh di gambar
                'block4_rate' => 0,    // Tidak ada blok IV pada contoh
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],

            // Golongan 3 - Besar/Komersial (Tarif Tinggi)
            [
                'code' => '3I1',
                'name' => 'Industri Kecil',
                'category' => 'Industri',
                'description' => 'Industri skala kecil',
                'block1_rate' => 6800,
                'block2_rate' => 7800,
                'block3_rate' => 8800,
                'block4_rate' => 9800,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3I1K',
                'name' => 'Industri Kecil (Kategori Khusus)',
                'category' => 'Industri',
                'description' => 'Industri kecil kategori khusus',
                'block1_rate' => 7000,
                'block2_rate' => 8000,
                'block3_rate' => 9000,
                'block4_rate' => 10000,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3I2',
                'name' => 'Industri Besar',
                'category' => 'Industri',
                'description' => 'Industri skala besar',
                'block1_rate' => 9500,
                'block2_rate' => 11000,
                'block3_rate' => 12500,
                'block4_rate' => 14000,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3I2K',
                'name' => 'Industri Besar (Kategori Khusus)',
                'category' => 'Industri',
                'description' => 'Industri besar kategori khusus',
                'block1_rate' => 9800,
                'block2_rate' => 11300,
                'block3_rate' => 12800,
                'block4_rate' => 14300,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3L1',
                'name' => 'Badan Usaha Milik Pemerintah',
                'category' => 'Lembaga',
                'description' => 'BUMN dan BUMD',
                'block1_rate' => 5500,
                'block2_rate' => 6300,
                'block3_rate' => 7100,
                'block4_rate' => 7900,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3N1',
                'name' => 'Niaga dan Jasa Besar',
                'category' => 'Niaga',
                'description' => 'Usaha niaga dan jasa skala besar',
                'block1_rate' => 8200,
                'block2_rate' => 9400,
                'block3_rate' => 10600,
                'block4_rate' => 11800,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3R1',
                'name' => 'Rumah Tinggal Besar',
                'category' => 'Rumah',
                'description' => 'Rumah dengan kriteria besar',
                'block1_rate' => 8500,
                'block2_rate' => 9700,
                'block3_rate' => 10900,
                'block4_rate' => 12100,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
            [
                'code' => '3R2',
                'name' => 'Rumah Tinggal Mewah/Peristirahatan',
                'category' => 'Rumah',
                'description' => 'Rumah mewah dan villa',
                'block1_rate' => 9200,
                'block2_rate' => 10600,
                'block3_rate' => 12000,
                'block4_rate' => 13400,
                'block1_limit' => 10,
                'block2_limit' => 10,
                'block3_limit' => 10,
            ],
        ];

        foreach ($customerGroups as $group) {
            DB::table('customer_groups')->insert(array_merge($group, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
